[project]
name = "laida"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "glances>=4.3.3",
    "ipython>=9.4.0",
    "matplotlib>=3.10.3",
    "streamlit>=1.47.1",
    "uvicorn>=0.35.0",
]
